
# Rules for authors
# Formal data structures

$ref: '#/definitions/Page'


definitions:
  Page:
    type: 'object'
    properties:
      blades:
        type: 'array'
        items:
          $ref: '#/definitions/Blade'


  Blade:
    oneOf:
      - $ref: '#/definitions/HeroBlade'
      - $ref: '#/definitions/FeatureBlade'


  HeroBlade:
    type: 'object'
    properties:
      blade:
        const: 'hero'
      image:
        type: 'string'
      title: 
        type: 'string'
      details: 
        type: 'string'
      button: 
        $ref: '#/definitions/Button'

  FeatureBlade:
    type: 'object'
    properties:
      blade:
        const: 'feature'
      featureItems:
        type: 'array'
        items:
          type: 'object'
          properties:
            image:
              type: 'string'
            productNews:
              type: 'string'
            about:
              type: 'string'

  Button:
    type: 'object'
    required:
      - 'label'
      - 'url'
    properties:
      label:
        type: 'string'
      url:
        type: 'string'
