
# Rules for authors
# Formal data structures

$ref: '#/definitions/Page'


definitions:
  Page:
    type: 'object'
    minProperties: 1
    additionalProperties: false
    properties:
      blades:
        type: 'array'
        items:
          $ref: '#/definitions/Blade'


  Blade:
    oneOf:
      - $ref: '#/definitions/HeroBlade'
      - $ref: '#/definitions/FeatureBlade'
      - $ref: '#/definitions/AboutBlade'
      - $ref: '#/definitions/TestimonialBlade'
      - $ref: '#/definitions/BestSellerBlade'
      - $ref: '#/definitions/LocationBlade'
      - $ref: '#/definitions/InstagramBlade'
      - $ref: '#/definitions/SignUpBlade'


  HeroBlade:
    type: 'object'
    minProperties: 5
    additionalProperties: false
    properties:
      blade:
        const: 'hero'
      image:
        type: 'string'
      title: 
        type: 'string'
      details: 
        type: 'string'
      buttonShopNow: 
        $ref: '#/definitions/ButtonShopNow'


  FeatureBlade:
    type: 'object'
    minProperties: 2
    additionalProperties: false
    properties:
      blade:
        const: 'feature'
      featuredItems:
        type: 'array'
        minItems: 3
        maxItems: 3
        items:
          type: 'object'
          properties:
            image:
              type: 'string'
            productNews:
              type: 'string'
            about:
              type: 'string'


  AboutBlade:
    type: 'object'
    minProperties: 3
    additionalProperties: false
    properties:
      blade:
        const: 'about'
      title:
        type: 'string'
      principleItems:
        type: 'array'
        minItems: 2
        maxItems: 2
        items:
          type: 'object'
          image:
            type: 'string'
          caption:
            type: 'string'
          buttonLearnMore:
            $ref: '#/definitions/ButtonLearnMore' 

  TestimonialBlade:
    type: 'object'
    minProperties: 3
    additionalProperties: false
    properties:
      blade:
        const: 'testimonial'
      title: 
        type: 'string'
      testimonialItems:
        type: 'array'
        minItems: 1
        maxItems: 5
        items:
          type: 'object'
          minProperties: 4
          additionalProperties: false
          properties:
            starReview:
              type: 'number'
            image:
              type: 'string'
            quote:
              type: 'string'
            name:
              type: 'string'

  BestSellerBlade:
    type: 'object'
    properties:
      blade:
        const: 'best-seller'
      bestSellerItems:
        type: 'array'
        items:
          type: 'object'
          minProperties: 2
          additionalProperties: false
          properties:
            image:
              type: 'string'
            buttonGender:
              $ref: '#/definitions/ButtonGender'

  LocationBlade:
    type: 'object'
    minProperties: 4
    additionalProperties: false
    properties:
      blade:
        const: 'location'
      title:
        type: 'string'
      body:
        type: 'string'
      image:
        type: 'string'


  InstagramBlade:
    type: 'object'
    minProperties: 4
    additionalProperties: false
    properties:
      blade:
        const: 'instagram'
      title:
        type: 'string'
      buttonSocial:
        $ref: '#/definitions/ButtonSocial'
      instagramItems:
        type: 'array'
        items:
          type: 'object'
          minProperties: 3
          additionalProperties: false
          properties:
            image:
              type: 'string'
            caption:
              type: 'string'
            url:
              type: 'string'
    

  SignUpBlade:
    type: 'object'
    minProperties: 3
    additionalProperties: false
    properties:
      blade:
        const: 'sign-up'
      title:
        type: 'string'
      buttonSignup:
        $ref:  '#/definitions/ButtonSignUp'


  ButtonSocial:
    type: 'object'
    minProperties: 2
    additionalProperties: false
    properties:
      label:
        type: 'string'
      url:
        type: 'string'


  ButtonSignUp:
    type: 'object'
    minProperties: 2
    additionalProperties: false
    properties:
      label: 
        type: 'string'
      url:
        type: 'string'

  ButtonShopNow:
    type: 'object'
    minProperties: 2
    additionalProperties: false
    properties:
      label:
        type: 'string'
      url:
        type: 'string'

  ButtonLearnMore:
    type: 'object'
    minProperties: 2
    additionalProperties: false
    properties:
      label:
        type: 'string'
      url:
        type: 'string'

  ButtonGender:
    type: 'object'
    minProperties: 2
    additionalProperties: false
    properties:
      label:
        type: 'string'
      url:
        type: 'string'

