
# Formal data structures

$ref: '#/definitions/Page'


definitions:
  Page:
    type: 'object'
    properties:
      blades:
        type: 'array'
        items:
          $ref: '#/definitions/HeroBlade'

  HeroBlade:
    type: 'object'
    properties:
      blade:
        const: 'hero'
      image:
        type: 'string'
      title: 
        type: 'string'
      details: 
        type: 'string'
      button: 
        type: 'object'
        required:
          - 'label'
          - 'url'
        properties:
          label:
            type: 'string'
          url:
            type: 'string'